### PR TITLE
Upgrade terraform framework plugin to v1.4.2

### PR DESCRIPTION
**Pull request by RayLiu7**
# Description
Terraform framework plugin 1.4.0 doesn't work with Terraform 1.6 due to a know issue (fixed in 1.4.1) and causes all FT cases to fail (Err: Data Source Type Not Found or Resource Type Not Found).
Issue: https://github.com/hashicorp/terraform-plugin-framework/issues/853
Upgrade its version to the latest 1.4.2 to solve the problem.
Pipeline: https://osj-sio-03-prd.cec.lab.emc.com/view/Terraform/job/Terraform-Pipelines/job/tf-manual/747/Summary_20Report/
The failed NFS export cases and Snapshot cases need feature FT owner's further investigation.

# ISSUE TYPE
- Bugfix Pull Request

##### OUTPUT
Pipeline: https://osj-sio-03-prd.cec.lab.emc.com/view/Terraform/job/Terraform-Pipelines/job/tf-manual/747/Summary_20Report/

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 80% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Unit tests
- [x] Acceptance tests

### CODE REVIEW

**Comment by RayLiu7** [comment]
run e2e test

**Comment by forrestxia** [comment]
run e2e test

**Comment by forrestxia** [comment]
run e2e test

**Comment by forrestxia** [comment]
e2e pass

**Review by forrestxia — APPROVED** [review]

**Comment by forrestxia** [comment]
@RayLiu7 need signed commit

**Review by NavisJ — APPROVED** [review]

**Comment by RayLiu7** [comment]
run e2e test

**Comment by RayLiu7** [comment]
e2e pass

**Pull request merged**
