### PR TITLE
Forbidden change user's sid

### PR DESCRIPTION
**Pull request by taohe1012**
# Description
Forbidden change user's sid.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# ISSUE TYPE

- Bugfix Pull Request

##### RESOURCE OR DATASOURCE NAME
User Resource

##### OUTPUT
All tests for user resource are passed.
image

image

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 80% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Unit tests
- [x] Acceptance tests

### CODE REVIEW

**Comment by taohe1012** [comment]
run e2e test

**Review by baoy1 — APPROVED** [review]

**Review by NavisJ — APPROVED** [review]

**Comment by taohe1012** [comment]
run e2e test

**Comment by taohe1012** [comment]
all tests for user resource are passed.

**Comment by taohe1012** [comment]
e2e pass

**Pull request merged**
