### PR TITLE
Snapshot restore

### PR DESCRIPTION
**Pull request by shenda1**
# Description
PR is raised to add snaprevert functionality for snapshot restore resource.

# ISSUE TYPE
- Feature Pull Request

##### RESOURCE OR DATASOURCE NAME

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 80% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Unit tests
- [x] Acceptance tests

image

### CODE REVIEW

**Comment by shenda1** [comment]
run e2e test SnapshotRestoreResource

**Comment by shenda1** [comment]
run e2e test SnapshotRestoreResource

**Comment by taohe1012** [comment]
sorry @shenda1 , I re-run the Terraform-main-CI / Generate and the action failed...
It's due to the 'go:generate terraform fmt -recursive ./examples/' in main.go.  
Hours ago, the action can pass, nut now Not sure why it cannot pass.
We may need to remove this line for now....

**Comment by shenda1** [comment]
run e2e test SnapshotRestoreResource

**Review by rounak-adhikary — APPROVED** [review]

**Comment by shenda1** [comment]
run e2e test SnapshotRestoreResource

**Comment by shenda1** [comment]
run e2e test SnapshotRestoreResource

**Review by Sakshi-dell — APPROVED** [review]
LGTM

**Pull request merged**
