### PR TITLE
adding support assist resource

### PR DESCRIPTION
**Pull request by shenda1**
# Description
PR is raised to add support assist resource

# ISSUE TYPE
- Feature Pull Request

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 80% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Unit tests
- [x] Acceptance tests

image

### CODE REVIEW

**Comment by shenda1** [comment]
run e2e test SupportAssistResource

**Comment by shenda1** [comment]
run e2e test SupportAssistResource

**Comment by shenda1** [comment]
run e2e test SupportAssistResource

**Comment by shenda1** [comment]
run e2e test

**Comment by shenda1** [comment]
run e2e test

**Comment by shenda1** [comment]
run e2e test SupportAssistResource

**Comment by shenda1** [comment]
run e2e test SupportAssistResource

**Comment by shenda1** [comment]
run e2e test SupportAssistResource

**Review by rounak-adhikary — APPROVED** [review]

**Review by Krunal-Thakkar — APPROVED** [review]

**Pull request merged**
