### PR TITLE
Adding validators to user and usergroup datasources

### PR DESCRIPTION
**Pull request by rounak-adhikary**

### CODE REVIEW

**Review by shenda1 — APPROVED** [review]

**Comment by rounak-adhikary** [comment]
run e2e test User

**Comment by rounak-adhikary** [comment]
run e2e test User|S3BucketDatasource

**Review by Krunal-Thakkar — APPROVED** [review]

**Comment by rounak-adhikary** [comment]
run e2e test User|S3BucketDatasource

**Comment by rounak-adhikary** [comment]
run e2e test User,S3BucketDatasource

**Pull request merged**
