### PR TITLE
Update validators for optional fields

### PR DESCRIPTION
**Pull request by nikitajoshi1**
# Description
Update validators for optional fields

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# ISSUE TYPE

- Bugfix Pull Request

##### RESOURCE OR DATASOURCE NAME
Snapshot Schedule

##### OUTPUT
invalid1
invalid3
invalid2

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 80% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Unit tests
- [x] Acceptance tests

### CODE REVIEW

**Review by doriac11 — APPROVED** [review]
Approve, once the things we talked about in slack are added.

**Comment by nikitajoshi1** [comment]
> Approve, once the things we talked about in slack are added.

Updated minimum validator too for alias as discussed

**Comment by nikitajoshi1** [comment]
run e2e test

**Comment by nikitajoshi1** [comment]
run e2e test

**Review by taohe1012 — APPROVED** [review]

**Pull request merged**
