### PR TITLE
Adding support for getting all paginated data in existing datasources

### PR DESCRIPTION
**Pull request by akshay-sripriya**
# Description
Adding support for getting all paginated data in existing datasources. Priorly datasources got only results from the first page.

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 80% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Unit tests
- [x] Acceptance tests

### CODE REVIEW

**Comment by terraform-providers-svc** [comment]
Can one of the admins verify this patch?

**Comment by akshay-sripriya** [comment]
run e2e test SnapshotScheduleDataSource

**Comment by akshay-sripriya** [comment]
run e2e test SnapshotScheduleDataSource

**Review by shenda1 — APPROVED** [review]

**Review by Sakshi-dell — APPROVED** [review]

**Comment by akshay-sripriya** [comment]
run e2e test SnapshotScheduleDataSource

**Pull request merged**
