### PR TITLE
network pool datasource feature

### PR DESCRIPTION
**Pull request by RayLiu7**
# Description
network pool datasource feature

# ISSUE TYPE
- Feature Pull Request

##### RESOURCE OR DATASOURCE NAME
network pool datasource

##### OUTPUT
image
image

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 80% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Unit tests
- [x] Acceptance tests

### CODE REVIEW

**Comment by RayLiu7** [comment]
run e2e test

**Comment by RayLiu7** [comment]
e2e pass

**Review by taohe1012 — APPROVED** [review]

**Comment by RayLiu7** [comment]
run e2e test

**Review by NavisJ — APPROVED** [review]

**Comment by RayLiu7** [comment]
run e2e test

**Pull request merged**
