### PR TITLE
Added fix for s3 bucket and smb share datasources filter bug

### PR DESCRIPTION
**Pull request by akshay-sripriya**
# Description
Added filter validation for invalid and empty cases in S3 Bucket and SMB Share Datasources

##### RESOURCE OR DATASOURCE NAME
S3 Bucket Datasource
SMB Share Datasource

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 80% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Unit tests
- [x] Acceptance tests

### CODE REVIEW

**Comment by akshay-sripriya** [comment]
run e2e TestAccSmbShareDatasource

**Comment by akshay-sripriya** [comment]
run e2e SmbShareDatasource

**Comment by akshay-sripriya** [comment]
run e2e test SmbShareDatasource

**Review by shenda1 — APPROVED** [review]

**Comment by Krunal-Thakkar** [comment]
run e2e test SmbShareDatasource

**Comment by akshay-sripriya** [comment]
image
image

**Review by Krunal-Thakkar — APPROVED** [review]

**Pull request merged**
