### PR TITLE
Update Terraform Plugin Version

### PR DESCRIPTION
**Pull request by NavisJ**
# Description
Update Terraform Plugin Version

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 80% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Unit tests
- [x] Acceptance tests

### CODE REVIEW

**Comment by forrestxia** [comment]
run e2e test

**Comment by NavisJ** [comment]
run e2e test

**Comment by NavisJ** [comment]
run e2e test

**Review by doriac11 — APPROVED** [review]

**Review by baoy1 — APPROVED** [review]

**Comment by forrestxia** [comment]
run e2e test

**Comment by forrestxia** [comment]
e2e pass

**Comment by forrestxia** [comment]
run e2e test

**Comment by forrestxia** [comment]
@NavisJ please check golangci-lint failure for this plugin framework change. The golang is upgraded from 1.20 to 1.21 now.

**Comment by NavisJ** [comment]
run e2e test

**Comment by NavisJ** [comment]
> @NavisJ please check golangci-lint failure for this plugin framework change. The golang is upgraded from 1.20 to 1.21 now.

@forrestxia 
I tried to run the command in my local env with 
```
golangci-lint has version 1.54.2 built with go1.21.0 from 411e0bbb on 2023-08-21T12:04:32Z
```
and 
```
golangci-lint has version 1.55.1 built with go1.21.3 from 9b20d49d on 2023-10-25T10:03:43Z
```
and they all run well.

The error is not introduced in this change cause it is also reported in  https://github.com/dell/terraform-provider-powerscale/pull/77

I resolved all the errors in https://osj-sio-03-prd.cec.lab.emc.com/job/Terraform-Pipelines/job/tf-manual/719/console
including `missing type in composite literal` and `dot import`
and now it reports
```
golangci-lint run --fix --timeout 5m
level=warning msg="[runner] Can't run linter goanalysis_metalinter: buildir: failed to load package sys: could not load export data: no export data for \"runtime/internal/sys\""
level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: buildir: failed to load package sys: could not load export data: no export data for \"runtime/internal/sys\"\n\n"
``` 
The dependency is golang internal package and not declared by us. After some investigation, the issue could be golint support matrix problem, like https://github.com/golangci/golangci-lint-action/issues/448
please check version `go version` and `golangci-lint --version` and ensure the version of golangci-lint is built with a compatible version of Go.

**Comment by forrestxia** [comment]
run e2e test

**Comment by NavisJ** [comment]
run e2e test

**Comment by NavisJ** [comment]
run e2e test

**Pull request merged**
