### PR TITLE
Update example usage for release 1.4

### PR DESCRIPTION
**Pull request by tanh17**
# Description
Update index.md to add new abridged cases

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# ISSUE TYPE

- Docs Pull Request

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 80% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Unit tests
- [ ] Acceptance tests

### CODE REVIEW

**Review by taohe1012 — APPROVED** [review]

**Review by RayLiu7 — APPROVED** [review]

**Comment by taohe1012** [comment]
hi @tanh17 , please squash 3 commits to one.

**Comment by tanh17** [comment]
run e2e test

**Comment by RayLiu7** [comment]
The commit should be signed @tanh17

**Review by MangirishK — COMMENTED** [review]
In provider.tf
the version is 1.1.0, should it be 1.4.0 ?
Also few resource examples are missing like nfs_zone_settings, smb_server_settings

**Comment by tanh17** [comment]
> In provider.tf the version is 1.1.0, should it be 1.4.0 ? Also few resource examples are missing like nfs_zone_settings, smb_server_settings

Hi Mangirish, I only add abridge case related resources, smb_server_settings is not included.

**Review by taohe1012 — APPROVED** [review]

**Review by MangirishK — APPROVED** [review]
For the newly added resource examples, please add their names in the Example Usage section in the index.md file

**Comment by tanh17** [comment]
run e2e test

**Pull request merged**
