### PR TITLE
Fix s3 bucket update issue

### PR DESCRIPTION
**Pull request by vangork**
# Description
1. Allow update zone from System to none or none to System. 
2. Fix update issue if create_path is set

# ISSUE TYPE

- Bugfix Pull Request

##### RESOURCE OR DATASOURCE NAME

s3_bucket_resoure

##### OUTPUT
image

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 80% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Unit tests
- [x] Acceptance tests

### CODE REVIEW

**Comment by vangork** [comment]
run e2e test

**Comment by taohe1012** [comment]
hi @vangork ,please rebase commits to one, thanks

**Comment by vangork** [comment]
> hi @vangork ,please rebase commits to one, thanks

Done.

**Comment by vangork** [comment]
run e2e test

**Review by taohe1012 — APPROVED** [review]

**Pull request merged**
