### PR TITLE
Support update zone name

### PR DESCRIPTION
**Pull request by P-Cao**
Though quota and smb share does not support zone modification, zone name could be renamed
Now fix bug during renaming access zone

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# ISSUE TYPE
- Bugfix Pull Request

##### OUTPUT

```paste below

```
##### ADDITIONAL INFORMATION

```paste below

```
# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 80% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Unit tests
- [ ] Acceptance tests

### CODE REVIEW

**Comment by P-Cao** [comment]
run e2e test

**Review by RayLiu7 — APPROVED** [review]

**Review by baoy1 — APPROVED** [review]
For the zone in nfs export, Cannot be changed once set.
What happens for nfs export if user updated zone in abridge case?

**Comment by tanh17** [comment]
> For the zone in nfs export, Cannot be changed once set. What happens for nfs export if user updated zone in abridge case?

Error updating nfs export when changing zone's name. The error message is "Do not change access zone once set".

**Comment by baoy1** [comment]
> > For the zone in nfs export, Cannot be changed once set. What happens for nfs export if user updated zone in abridge case?
> 
> Error updating nfs export when changing zone's name. The error message is "Do not change access zone once set".

There are two scenarios, 1, update zone in nfs export payload, that is not permitted based on the code design. We show "Do not change access zone once set".  2. rename zone resource in abridge scenario, will terraform perform update on nfs export, then show "Do not change access zone once set"?
Based on UI, after renaming zone, nfs export is still visible under the zone.

**Pull request merged**
