### PR TITLE
Synciq Peer Certificate: Add name filter to  Ds + Remove ID import Rs

### PR DESCRIPTION
**Pull request by rounak-adhikary**
Also, for peer cert res, only import by name makes sense.

### CODE REVIEW

**Comment by rounak-adhikary** [comment]
rune2e test SyncIQPeerCertificate

**Review by shenda1 — APPROVED** [review]

**Comment by rounak-adhikary** [comment]
run e2e test SyncIQPeerCertificate

**Comment by rounak-adhikary** [comment]
run e2e test SyncIQPeerCertificate

**Comment by rounak-adhikary** [comment]
run e2e test SyncIQPeerCertificate

**Pull request merged**
