### PR TITLE
Update go-client for PowerScale9.5

### PR DESCRIPTION
**Pull request by baoy1**
# Description
Update go-client for PowerScale9.5.

Note it is deliberate to have 3 commits in this PR. The first commit is used to add PowerScale 9.5 json file. The second commit is used to update Maximum values, which contains numerous changes; the third commit is used to update other fields.
Two separate commits is helpful as a reference to future json update.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### OUTPUT

```paste below

```
##### ADDITIONAL INFORMATION

```paste below

```
# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 80% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Unit tests
- [x] Acceptance tests

### CODE REVIEW

**Comment by baoy1** [comment]
run e2e test

**Review by RayLiu7 — APPROVED** [review]

**Review by doriac11 — APPROVED** [review]

**Comment by doriac11** [comment]
Did you do a AT run against the actual array? 
Could you do that and include the results in the description of the PR before merging?

**Comment by baoy1** [comment]
> Did you do a AT run against the actual array? Could you do that and include the results in the description of the PR before merging?

Good point! Test against actual array failed due to array restart... I will check that with @forrestxia

**Review by taohe1012 — APPROVED** [review]

**Review by NavisJ — APPROVED** [review]

**Comment by baoy1** [comment]
> Did you do a AT run against the actual array? Could you do that and include the results in the description of the PR before merging?

Hi @doriac11 , I just recall after raising the PR, I executed "run e2e test" that triggered an AT test on actual array,  see this [Jekins run](https://[osj-sio-03-prd.cec.lab.emc.com/job/Terraform-Pipelines/job/tf-powerscale-pr/269/consoleText](https://osj-sio-03-prd.cec.lab.emc.com/job/Terraform-Pipelines/job/tf-powerscale-pr/269/consoleText)).

**Comment by baoy1** [comment]
e2e pass

**Pull request closed without merging**
